<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.3.450">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Vivian O">

<title>Project 1: Duolingo Spaced Repetition Data</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="hp1_files/libs/clipboard/clipboard.min.js"></script>
<script src="hp1_files/libs/quarto-html/quarto.js"></script>
<script src="hp1_files/libs/quarto-html/popper.min.js"></script>
<script src="hp1_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="hp1_files/libs/quarto-html/anchor.min.js"></script>
<link href="hp1_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="hp1_files/libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="hp1_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="hp1_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="hp1_files/libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">


</head>

<body class="fullcontent">

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">

<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Project 1: Duolingo Spaced Repetition Data</h1>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Vivian O </p>
          </div>
  </div>
    
  
    
  </div>
  

</header>

<section id="important-before-starting" class="level3">
<h3 class="anchored" data-anchor-id="important-before-starting"><strong>IMPORTANT BEFORE STARTING:</strong></h3>
<p>If you do not have yet, please download the data set from source below and add it into your working folder.</p>
<p>Source: https://www.kaggle.com/datasets/aravinii/duolingo-spaced-repetition-data?resource=download</p>
<p>“Duolingo is an American educational technology company that produces learning apps and provides language certification. There main app is considered the most popular language learning app in the world.</p>
<p>To progress in their learning journey, each user of the application needs to complete a set of lessons in which they are presented with the words of the language they want to learn. In an infinite set of lessons, each word is applied in a different context and, on top of that, Duolingo uses a spaced repetition approach, where the user sees an already known word again to reinforce their learning.</p>
<p>Each line in this file refers to a Duolingo lesson that had a target word to practice.”</p>
</section>
<section id="questions-for-exploration" class="level3">
<h3 class="anchored" data-anchor-id="questions-for-exploration"><strong>Questions for Exploration:</strong></h3>
<p><strong>1. How effective is the spaced repetition approach employed by Duolingo?</strong></p>
<p><strong>2. Are there any patterns in user performance based on time since the last practice?</strong></p>
<p><strong>3. Does the user interface language affect the user’s performance?</strong></p>
<p><strong>4. What are the most challenging lexemes for users?</strong></p>
<p><strong>5. Is there any correlation between the user’s history with a word and their performance in the current session?</strong></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Load necessary libraries</span></span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: package 'tidyverse' was built under R version 4.2.3</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: package 'ggplot2' was built under R version 4.2.3</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: package 'tibble' was built under R version 4.2.3</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: package 'tidyr' was built under R version 4.2.3</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: package 'readr' was built under R version 4.2.3</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: package 'purrr' was built under R version 4.2.3</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: package 'dplyr' was built under R version 4.2.3</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: package 'forcats' was built under R version 4.2.3</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: package 'lubridate' was built under R version 4.2.3</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>── Attaching core tidyverse packages ──────────────────────── tidyverse 2.0.0 ──
✔ dplyr     1.1.4     ✔ readr     2.1.5
✔ forcats   1.0.0     ✔ stringr   1.5.0
✔ ggplot2   3.4.2     ✔ tibble    3.2.1
✔ lubridate 1.9.3     ✔ tidyr     1.3.0
✔ purrr     1.0.2     
── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──
✖ dplyr::filter() masks stats::filter()
✖ dplyr::lag()    masks stats::lag()
ℹ Use the conflicted package (&lt;http://conflicted.r-lib.org/&gt;) to force all conflicts to become errors</code></pre>
</div>
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(readr)</span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(stringr)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Set working directory if needed</span></span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a><span class="fu">setwd</span>(<span class="st">"C:/Users/kvho5/OneDrive/Documents/LING343/O_hp1"</span>)</span>
<span id="cb13-3"><a href="#cb13-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-4"><a href="#cb13-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Define the path to the compressed file</span></span>
<span id="cb13-5"><a href="#cb13-5" aria-hidden="true" tabindex="-1"></a>compressed_file <span class="ot">&lt;-</span> <span class="st">"C:/Users/kvho5/OneDrive/Documents/LING343/O_hp1/settles.acl16.learning_traces.13m.csv.gz"</span></span>
<span id="cb13-6"><a href="#cb13-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-7"><a href="#cb13-7" aria-hidden="true" tabindex="-1"></a><span class="co"># Define the path where you want to extract the C</span></span>
<span id="cb13-8"><a href="#cb13-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-9"><a href="#cb13-9" aria-hidden="true" tabindex="-1"></a>output_directory <span class="ot">&lt;-</span> <span class="st">"C:/Users/kvho5/OneDrive/Documents/LING343/O_hp1/"</span></span>
<span id="cb13-10"><a href="#cb13-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-11"><a href="#cb13-11" aria-hidden="true" tabindex="-1"></a><span class="co"># Unzipping the file</span></span>
<span id="cb13-12"><a href="#cb13-12" aria-hidden="true" tabindex="-1"></a><span class="fu">unzip</span>(compressed_file, <span class="at">exdir =</span> output_directory)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in unzip(compressed_file, exdir = output_directory): error 1 in
extracting from zip file</code></pre>
</div>
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Defining the path to the unzipped CSV file</span></span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a>unzipped_file <span class="ot">&lt;-</span><span class="st">"C:/Users/kvho5/OneDrive/Documents/LING343/O_hp1/settles.acl16.learning_traces.13m.csv.gz"</span></span>
<span id="cb15-3"><a href="#cb15-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-4"><a href="#cb15-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Reading the CSV file</span></span>
<span id="cb15-5"><a href="#cb15-5" aria-hidden="true" tabindex="-1"></a>duo_data <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(unzipped_file)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Rows: 12854226 Columns: 12
── Column specification ────────────────────────────────────────────────────────
Delimiter: ","
chr (5): user_id, learning_language, ui_language, lexeme_id, lexeme_string
dbl (7): p_recall, timestamp, delta, history_seen, history_correct, session_...

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.</code></pre>
</div>
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Displaying the first few rows of the dataset</span></span>
<span id="cb17-2"><a href="#cb17-2" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(duo_data)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 6 × 12
  p_recall  timestamp    delta user_id learning_language ui_language lexeme_id  
     &lt;dbl&gt;      &lt;dbl&gt;    &lt;dbl&gt; &lt;chr&gt;   &lt;chr&gt;             &lt;chr&gt;       &lt;chr&gt;      
1      1   1362076081 27649635 u:FO    de                en          76390c1350…
2      0.5 1362076081 27649635 u:FO    de                en          7dfd7086f3…
3      1   1362076081 27649635 u:FO    de                en          35a54c25a2…
4      0.5 1362076081 27649635 u:FO    de                en          0cf63ffe3d…
5      1   1362076081 27649635 u:FO    de                en          84920990d7…
6      1   1362076081 27649635 u:FO    de                en          56429751fd…
# ℹ 5 more variables: lexeme_string &lt;chr&gt;, history_seen &lt;dbl&gt;,
#   history_correct &lt;dbl&gt;, session_seen &lt;dbl&gt;, session_correct &lt;dbl&gt;</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Checking what are the names and data types of each column</span></span>
<span id="cb19-2"><a href="#cb19-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-3"><a href="#cb19-3" aria-hidden="true" tabindex="-1"></a><span class="fu">spec</span>(duo_data)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>cols(
  p_recall = col_double(),
  timestamp = col_double(),
  delta = col_double(),
  user_id = col_character(),
  learning_language = col_character(),
  ui_language = col_character(),
  lexeme_id = col_character(),
  lexeme_string = col_character(),
  history_seen = col_double(),
  history_correct = col_double(),
  session_seen = col_double(),
  session_correct = col_double()
)</code></pre>
</div>
</div>
<p>“The columns are as follows:</p>
<ul>
<li><p><code>p_recall</code> - proportion of exercises from this lesson/practice where the word/lexeme was correctly recalled</p></li>
<li><p><code>timestamp</code> - UNIX timestamp of the current lesson/practice</p></li>
<li><p><code>delta</code> - time (in seconds) since the last lesson/practice that included this word/lexeme</p></li>
<li><p><code>user_id</code> - student user ID who did the lesson/practice (anonymized)</p></li>
<li><p><code>learning_language</code> - language being learned</p></li>
<li><p><code>ui_language</code> - user interface language (presumably native to the student)</p></li>
<li><p><code>lexeme_id</code> - system ID for the lexeme tag (i.e., word)</p></li>
<li><p><code>lexeme_string</code> - lexeme tag (see below)</p></li>
<li><p><code>history_seen</code> - total times user has seen the word/lexeme prior to this lesson/practice</p></li>
<li><p><code>history_correct</code> - total times user has been correct for the word/lexeme prior to this lesson/practice</p></li>
<li><p><code>session_seen</code> - times the user saw the word/lexeme during this lesson/practice</p></li>
<li><p><code>session_correct</code> - times the user got the word/lexeme correct during this lesson/practice</p></li>
</ul>
<p>The lexeme_string column contains a string representation of the “lexeme tag” used by Duolingo for each lesson/practice (data instance) in our experiments. The lexeme_string field uses the following format:</p>
<p>`surface-form/lemma”</p>
</section>
<section id="data-cleaning-and-tidying" class="level3">
<h3 class="anchored" data-anchor-id="data-cleaning-and-tidying"><strong>Data Cleaning and Tidying</strong></h3>
<p>In this step, I will be handling missing values, renaming variables (if needed), and setting appropriate variable types.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb21"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Checking for missing values</span></span>
<span id="cb21-2"><a href="#cb21-2" aria-hidden="true" tabindex="-1"></a><span class="fu">sum</span>(<span class="fu">is.na</span>(duo_data))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0</code></pre>
</div>
<div class="sourceCode cell-code" id="cb23"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Output: 0 so there are no missing values.</span></span>
<span id="cb23-2"><a href="#cb23-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-3"><a href="#cb23-3" aria-hidden="true" tabindex="-1"></a><span class="co"># No renaming needed</span></span>
<span id="cb23-4"><a href="#cb23-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-5"><a href="#cb23-5" aria-hidden="true" tabindex="-1"></a><span class="co"># Setting appropriate variable types</span></span>
<span id="cb23-6"><a href="#cb23-6" aria-hidden="true" tabindex="-1"></a>duo_data<span class="sc">$</span>timestamp <span class="ot">&lt;-</span> <span class="fu">as.POSIXct</span>(duo_data<span class="sc">$</span>timestamp, <span class="at">origin =</span> <span class="st">"1970-01-01"</span>)</span>
<span id="cb23-7"><a href="#cb23-7" aria-hidden="true" tabindex="-1"></a>duo_data<span class="sc">$</span>user_id <span class="ot">&lt;-</span> <span class="fu">as.factor</span>(duo_data<span class="sc">$</span>user_id)</span>
<span id="cb23-8"><a href="#cb23-8" aria-hidden="true" tabindex="-1"></a>duo_data<span class="sc">$</span>learning_language <span class="ot">&lt;-</span> <span class="fu">as.factor</span>(duo_data<span class="sc">$</span>learning_language)</span>
<span id="cb23-9"><a href="#cb23-9" aria-hidden="true" tabindex="-1"></a>duo_data<span class="sc">$</span>ui_language <span class="ot">&lt;-</span> <span class="fu">as.factor</span>(duo_data<span class="sc">$</span>ui_language)</span>
<span id="cb23-10"><a href="#cb23-10" aria-hidden="true" tabindex="-1"></a>duo_data<span class="sc">$</span>lexeme_id <span class="ot">&lt;-</span> <span class="fu">as.factor</span>(duo_data<span class="sc">$</span>lexeme_id)</span>
<span id="cb23-11"><a href="#cb23-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-12"><a href="#cb23-12" aria-hidden="true" tabindex="-1"></a><span class="co"># Checking what are the languages found in the data set</span></span>
<span id="cb23-13"><a href="#cb23-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-14"><a href="#cb23-14" aria-hidden="true" tabindex="-1"></a>unique_learning_languages <span class="ot">&lt;-</span> <span class="fu">unique</span>(duo_data<span class="sc">$</span>learning_language)</span>
<span id="cb23-15"><a href="#cb23-15" aria-hidden="true" tabindex="-1"></a>unique_learning_languages</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] de es pt en fr it
Levels: de en es fr it pt</code></pre>
</div>
<div class="sourceCode cell-code" id="cb25"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Unique UI languages</span></span>
<span id="cb25-2"><a href="#cb25-2" aria-hidden="true" tabindex="-1"></a>unique_ui_languages <span class="ot">&lt;-</span> <span class="fu">unique</span>(duo_data<span class="sc">$</span>ui_language) </span>
<span id="cb25-3"><a href="#cb25-3" aria-hidden="true" tabindex="-1"></a>unique_ui_languages</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] en pt es it
Levels: en es it pt</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb27"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Using mutate and functions from stringr to change the language abbreviations to it's full name</span></span>
<span id="cb27-2"><a href="#cb27-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb27-3"><a href="#cb27-3" aria-hidden="true" tabindex="-1"></a><span class="co"># Replacing learning_language abbreviations with full names</span></span>
<span id="cb27-4"><a href="#cb27-4" aria-hidden="true" tabindex="-1"></a>duo_data <span class="ot">&lt;-</span> <span class="fu">mutate</span>(duo_data,</span>
<span id="cb27-5"><a href="#cb27-5" aria-hidden="true" tabindex="-1"></a>                   <span class="at">learning_language =</span> <span class="fu">str_replace</span>(learning_language, <span class="st">"de"</span>, <span class="st">"German"</span>),</span>
<span id="cb27-6"><a href="#cb27-6" aria-hidden="true" tabindex="-1"></a>                   <span class="at">learning_language =</span> <span class="fu">str_replace</span>(learning_language, <span class="st">"en"</span>, <span class="st">"English"</span>),</span>
<span id="cb27-7"><a href="#cb27-7" aria-hidden="true" tabindex="-1"></a>                   <span class="at">learning_language =</span> <span class="fu">str_replace</span>(learning_language, <span class="st">"es"</span>, <span class="st">"Spanish"</span>),</span>
<span id="cb27-8"><a href="#cb27-8" aria-hidden="true" tabindex="-1"></a>                   <span class="at">learning_language =</span> <span class="fu">str_replace</span>(learning_language, <span class="st">"fr"</span>, <span class="st">"French"</span>),</span>
<span id="cb27-9"><a href="#cb27-9" aria-hidden="true" tabindex="-1"></a>                   <span class="at">learning_language =</span> <span class="fu">str_replace</span>(learning_language, <span class="st">"it"</span>, <span class="st">"Italian"</span>),</span>
<span id="cb27-10"><a href="#cb27-10" aria-hidden="true" tabindex="-1"></a>                   <span class="at">learning_language =</span> <span class="fu">str_replace</span>(learning_language, <span class="st">"pt"</span>, <span class="st">"Portuguese"</span>))</span>
<span id="cb27-11"><a href="#cb27-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb27-12"><a href="#cb27-12" aria-hidden="true" tabindex="-1"></a><span class="co"># Replacing ui_language abbreviations with full names</span></span>
<span id="cb27-13"><a href="#cb27-13" aria-hidden="true" tabindex="-1"></a>duo_data <span class="ot">&lt;-</span> <span class="fu">mutate</span>(duo_data,</span>
<span id="cb27-14"><a href="#cb27-14" aria-hidden="true" tabindex="-1"></a>                   <span class="at">ui_language =</span> <span class="fu">str_replace</span>(ui_language, <span class="st">"en"</span>, <span class="st">"English"</span>),</span>
<span id="cb27-15"><a href="#cb27-15" aria-hidden="true" tabindex="-1"></a>                   <span class="at">ui_language =</span> <span class="fu">str_replace</span>(ui_language, <span class="st">"es"</span>, <span class="st">"Spanish"</span>),</span>
<span id="cb27-16"><a href="#cb27-16" aria-hidden="true" tabindex="-1"></a>                   <span class="at">ui_language =</span> <span class="fu">str_replace</span>(ui_language, <span class="st">"it"</span>, <span class="st">"Italian"</span>),</span>
<span id="cb27-17"><a href="#cb27-17" aria-hidden="true" tabindex="-1"></a>                   <span class="at">ui_language =</span> <span class="fu">str_replace</span>(ui_language, <span class="st">"pt"</span>, <span class="st">"Portuguese"</span>))</span>
<span id="cb27-18"><a href="#cb27-18" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb27-19"><a href="#cb27-19" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(duo_data)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 6 × 12
  p_recall timestamp              delta user_id learning_language ui_language
     &lt;dbl&gt; &lt;dttm&gt;                 &lt;dbl&gt; &lt;fct&gt;   &lt;chr&gt;             &lt;chr&gt;      
1      1   2013-02-28 13:28:01 27649635 u:FO    German            English    
2      0.5 2013-02-28 13:28:01 27649635 u:FO    German            English    
3      1   2013-02-28 13:28:01 27649635 u:FO    German            English    
4      0.5 2013-02-28 13:28:01 27649635 u:FO    German            English    
5      1   2013-02-28 13:28:01 27649635 u:FO    German            English    
6      1   2013-02-28 13:28:01 27649635 u:FO    German            English    
# ℹ 6 more variables: lexeme_id &lt;fct&gt;, lexeme_string &lt;chr&gt;, history_seen &lt;dbl&gt;,
#   history_correct &lt;dbl&gt;, session_seen &lt;dbl&gt;, session_correct &lt;dbl&gt;</code></pre>
</div>
<div class="sourceCode cell-code" id="cb29"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Checking the structure of the dataset</span></span>
<span id="cb29-2"><a href="#cb29-2" aria-hidden="true" tabindex="-1"></a><span class="fu">str</span>(duo_data)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>tibble [12,854,226 × 12] (S3: tbl_df/tbl/data.frame)
 $ p_recall         : num [1:12854226] 1 0.5 1 0.5 1 1 1 1 1 0.75 ...
 $ timestamp        : POSIXct[1:12854226], format: "2013-02-28 13:28:01" "2013-02-28 13:28:01" ...
 $ delta            : num [1:12854226] 27649635 27649635 27649635 27649635 27649635 ...
 $ user_id          : Factor w/ 115222 levels "u:--N","u:--U",..: 23179 23179 23179 23179 23179 23179 23179 9029 23179 23179 ...
 $ learning_language: chr [1:12854226] "German" "German" "German" "German" ...
 $ ui_language      : chr [1:12854226] "English" "English" "English" "English" ...
 $ lexeme_id        : Factor w/ 19279 levels "00022efc4121667defd065c88569e748",..: 8976 9578 4016 956 10074 6521 2039 8798 8976 9578 ...
 $ lexeme_string    : chr [1:12854226] "lernt/lernen&lt;vblex&gt;&lt;pri&gt;&lt;p3&gt;&lt;sg&gt;" "die/die&lt;det&gt;&lt;def&gt;&lt;f&gt;&lt;sg&gt;&lt;nom&gt;" "mann/mann&lt;n&gt;&lt;m&gt;&lt;sg&gt;&lt;nom&gt;" "frau/frau&lt;n&gt;&lt;f&gt;&lt;sg&gt;&lt;nom&gt;" ...
 $ history_seen     : num [1:12854226] 6 4 5 6 4 4 4 3 8 6 ...
 $ history_correct  : num [1:12854226] 4 4 4 5 4 3 4 3 6 5 ...
 $ session_seen     : num [1:12854226] 2 2 1 2 1 1 1 1 6 4 ...
 $ session_correct  : num [1:12854226] 2 1 1 1 1 1 1 1 6 3 ...</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb31"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb31-1"><a href="#cb31-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Creating a new column with the history_recall ratio</span></span>
<span id="cb31-2"><a href="#cb31-2" aria-hidden="true" tabindex="-1"></a>duo_data <span class="ot">&lt;-</span> duo_data <span class="sc">|&gt;</span></span>
<span id="cb31-3"><a href="#cb31-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">history_recall =</span> history_correct <span class="sc">/</span> history_seen)</span>
<span id="cb31-4"><a href="#cb31-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb31-5"><a href="#cb31-5" aria-hidden="true" tabindex="-1"></a><span class="co"># Viewing the updated data frame</span></span>
<span id="cb31-6"><a href="#cb31-6" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(duo_data)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 6 × 13
  p_recall timestamp              delta user_id learning_language ui_language
     &lt;dbl&gt; &lt;dttm&gt;                 &lt;dbl&gt; &lt;fct&gt;   &lt;chr&gt;             &lt;chr&gt;      
1      1   2013-02-28 13:28:01 27649635 u:FO    German            English    
2      0.5 2013-02-28 13:28:01 27649635 u:FO    German            English    
3      1   2013-02-28 13:28:01 27649635 u:FO    German            English    
4      0.5 2013-02-28 13:28:01 27649635 u:FO    German            English    
5      1   2013-02-28 13:28:01 27649635 u:FO    German            English    
6      1   2013-02-28 13:28:01 27649635 u:FO    German            English    
# ℹ 7 more variables: lexeme_id &lt;fct&gt;, lexeme_string &lt;chr&gt;, history_seen &lt;dbl&gt;,
#   history_correct &lt;dbl&gt;, session_seen &lt;dbl&gt;, session_correct &lt;dbl&gt;,
#   history_recall &lt;dbl&gt;</code></pre>
</div>
</div>
<p>I will also be making a new data frame that encompass data focused on each unique user_ids rather than target word</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb33"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb33-1"><a href="#cb33-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Calculating the avg of history_recall and p_recall of all tested words for each user_id</span></span>
<span id="cb33-2"><a href="#cb33-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb33-3"><a href="#cb33-3" aria-hidden="true" tabindex="-1"></a>user_summary <span class="ot">&lt;-</span> duo_data <span class="sc">|&gt;</span></span>
<span id="cb33-4"><a href="#cb33-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(user_id) <span class="sc">|&gt;</span></span>
<span id="cb33-5"><a href="#cb33-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarize</span>(<span class="at">avg_history_recall =</span> <span class="fu">mean</span>(history_recall, <span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb33-6"><a href="#cb33-6" aria-hidden="true" tabindex="-1"></a>            <span class="at">avg_p_recall =</span> <span class="fu">mean</span>(p_recall, <span class="at">na.rm =</span> <span class="cn">TRUE</span>)) <span class="sc">|&gt;</span></span>
<span id="cb33-7"><a href="#cb33-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ungroup</span>()</span>
<span id="cb33-8"><a href="#cb33-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb33-9"><a href="#cb33-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb33-10"><a href="#cb33-10" aria-hidden="true" tabindex="-1"></a>user_summary</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 115,222 × 3
   user_id avg_history_recall avg_p_recall
   &lt;fct&gt;                &lt;dbl&gt;        &lt;dbl&gt;
 1 u:--N                0.875        0.810
 2 u:--U                0.905        0.929
 3 u:-_-                0.912        0.905
 4 u:-_D                0.929        0.5  
 5 u:-3I                0.905        0.9  
 6 u:-3n                0.894        0.830
 7 u:-4V                0.932        0.874
 8 u:-4y                0.919        0.944
 9 u:-5I                0.801        0.885
10 u:-69                0.892        0.811
# ℹ 115,212 more rows</code></pre>
</div>
<div class="sourceCode cell-code" id="cb35"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb35-1"><a href="#cb35-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Reshaping the summarized data to wide format using pivot_wider()</span></span>
<span id="cb35-2"><a href="#cb35-2" aria-hidden="true" tabindex="-1"></a>wide_data <span class="ot">&lt;-</span> user_summary <span class="sc">|&gt;</span></span>
<span id="cb35-3"><a href="#cb35-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">pivot_wider</span>(<span class="at">names_from =</span> user_id, <span class="at">values_from =</span> <span class="fu">c</span>(avg_history_recall, avg_p_recall))</span>
<span id="cb35-4"><a href="#cb35-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb35-5"><a href="#cb35-5" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(wide_data)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 1 × 230,444
  `avg_history_recall_u:--N` `avg_history_recall_u:--U` avg_history_recall_u:-…¹
                       &lt;dbl&gt;                      &lt;dbl&gt;                    &lt;dbl&gt;
1                      0.875                      0.905                    0.912
# ℹ abbreviated name: ¹​`avg_history_recall_u:-_-`
# ℹ 230,441 more variables: `avg_history_recall_u:-_D` &lt;dbl&gt;,
#   `avg_history_recall_u:-3I` &lt;dbl&gt;, `avg_history_recall_u:-3n` &lt;dbl&gt;,
#   `avg_history_recall_u:-4V` &lt;dbl&gt;, `avg_history_recall_u:-4y` &lt;dbl&gt;,
#   `avg_history_recall_u:-5I` &lt;dbl&gt;, `avg_history_recall_u:-69` &lt;dbl&gt;,
#   `avg_history_recall_u:-7F` &lt;dbl&gt;, `avg_history_recall_u:-7U` &lt;dbl&gt;,
#   `avg_history_recall_u:-8a` &lt;dbl&gt;, `avg_history_recall_u:-Aa` &lt;dbl&gt;, …</code></pre>
</div>
<div class="sourceCode cell-code" id="cb37"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb37-1"><a href="#cb37-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Reshaping the wide-format data to long format using pivot_longer()</span></span>
<span id="cb37-2"><a href="#cb37-2" aria-hidden="true" tabindex="-1"></a><span class="co">#long_data &lt;- wide_data |&gt;</span></span>
<span id="cb37-3"><a href="#cb37-3" aria-hidden="true" tabindex="-1"></a>  <span class="co">#pivot_longer(cols = starts_with("avg_"), </span></span>
<span id="cb37-4"><a href="#cb37-4" aria-hidden="true" tabindex="-1"></a>               <span class="co">#names_to = c(".value", "type", "identifier"), </span></span>
<span id="cb37-5"><a href="#cb37-5" aria-hidden="true" tabindex="-1"></a>               <span class="co">#names_sep = ":--",</span></span>
<span id="cb37-6"><a href="#cb37-6" aria-hidden="true" tabindex="-1"></a>               <span class="co">#values_to = "value")</span></span>
<span id="cb37-7"><a href="#cb37-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-8"><a href="#cb37-8" aria-hidden="true" tabindex="-1"></a><span class="co"># View the long-format data</span></span>
<span id="cb37-9"><a href="#cb37-9" aria-hidden="true" tabindex="-1"></a><span class="co">#head(long_data)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb38"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb38-1"><a href="#cb38-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Calculate the number of times each unique user_id appears in duo_data</span></span>
<span id="cb38-2"><a href="#cb38-2" aria-hidden="true" tabindex="-1"></a>user_counts <span class="ot">&lt;-</span> duo_data <span class="sc">%&gt;%</span></span>
<span id="cb38-3"><a href="#cb38-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(user_id) <span class="sc">%&gt;%</span></span>
<span id="cb38-4"><a href="#cb38-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarize</span>(<span class="at">num_occurrences =</span> <span class="fu">n</span>())</span>
<span id="cb38-5"><a href="#cb38-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb38-6"><a href="#cb38-6" aria-hidden="true" tabindex="-1"></a><span class="co"># Calculate the average delta for each user_id</span></span>
<span id="cb38-7"><a href="#cb38-7" aria-hidden="true" tabindex="-1"></a>avg_delta <span class="ot">&lt;-</span> duo_data <span class="sc">%&gt;%</span></span>
<span id="cb38-8"><a href="#cb38-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(user_id) <span class="sc">%&gt;%</span></span>
<span id="cb38-9"><a href="#cb38-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarize</span>(<span class="at">avg_delta =</span> <span class="fu">mean</span>(delta, <span class="at">na.rm =</span> <span class="cn">TRUE</span>))</span>
<span id="cb38-10"><a href="#cb38-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb38-11"><a href="#cb38-11" aria-hidden="true" tabindex="-1"></a>user_summary <span class="ot">&lt;-</span> <span class="fu">left_join</span>(user_summary, user_counts, <span class="at">by =</span> <span class="st">"user_id"</span>)</span>
<span id="cb38-12"><a href="#cb38-12" aria-hidden="true" tabindex="-1"></a>user_summary <span class="ot">&lt;-</span> <span class="fu">left_join</span>(user_summary, avg_delta, <span class="at">by =</span> <span class="st">"user_id"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb39"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb39-1"><a href="#cb39-1" aria-hidden="true" tabindex="-1"></a>user_summary</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 115,222 × 5
   user_id avg_history_recall avg_p_recall num_occurrences avg_delta
   &lt;fct&gt;                &lt;dbl&gt;        &lt;dbl&gt;           &lt;int&gt;     &lt;dbl&gt;
 1 u:--N                0.875        0.810              32 15105609.
 2 u:--U                0.905        0.929               7  5608727 
 3 u:-_-                0.912        0.905             152   671605.
 4 u:-_D                0.929        0.5                14 12767600.
 5 u:-3I                0.905        0.9                14   283420.
 6 u:-3n                0.894        0.830             124 11269398.
 7 u:-4V                0.932        0.874             215  3142199.
 8 u:-4y                0.919        0.944              68  5354884.
 9 u:-5I                0.801        0.885              39   629067.
10 u:-69                0.892        0.811              15 13550005.
# ℹ 115,212 more rows</code></pre>
</div>
</div>
<p><em>Note: Interestingly, it appears the data set collected information from 100 unique participants. This was not informed on the kaggle website</em></p>
</section>
<section id="exploratory-data-analysis" class="level3">
<h3 class="anchored" data-anchor-id="exploratory-data-analysis"><strong>Exploratory Data Analysis</strong></h3>
<p>Now, I will proceed with exploring the data and answering the questions that were previously mentioned.</p>
<p><strong>1. How effective is the spaced repetition approach employed by Duolingo?</strong></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb41"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb41-1"><a href="#cb41-1" aria-hidden="true" tabindex="-1"></a>spaced_repetition_effectiveness <span class="ot">&lt;-</span> duo_data <span class="sc">|&gt;</span></span>
<span id="cb41-2"><a href="#cb41-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(lexeme_id) <span class="sc">|&gt;</span></span>
<span id="cb41-3"><a href="#cb41-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="at">avg_p_recall =</span> <span class="fu">mean</span>(p_recall))</span>
<span id="cb41-4"><a href="#cb41-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb41-5"><a href="#cb41-5" aria-hidden="true" tabindex="-1"></a>spaced_repetition_effectiveness</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 19,279 × 2
   lexeme_id                        avg_p_recall
   &lt;fct&gt;                                   &lt;dbl&gt;
 1 00022efc4121667defd065c88569e748        0.798
 2 00064bf8c1c3cefa80b193acf7b9fe1d        0.628
 3 000b96cf611dad846fda922f6e568298        1    
 4 000d2eb6a5658fa17f828c5fb0c66c11        0.910
 5 000f3063358c188d171d903ec5a7855c        0.819
 6 001635bcb24496cf2b27731c3708dbfa        0.941
 7 001973dce2d92d8d691f7ee9620c0c59        0.833
 8 001d7ebf4f57d36de6a98348294ec07f        0.667
 9 0022e9c57d77dc7992f3aea7be6a53bc        0.908
10 0023799f4a7ed08c8dc3591efee8c049        0.957
# ℹ 19,269 more rows</code></pre>
</div>
<div class="sourceCode cell-code" id="cb43"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb43-1"><a href="#cb43-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Summary statistics</span></span>
<span id="cb43-2"><a href="#cb43-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(spaced_repetition_effectiveness<span class="sc">$</span>avg_p_recall)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
 0.0000  0.8310  0.9013  0.8674  0.9746  1.0000 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb45"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb45-1"><a href="#cb45-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Histogram to explore the distribution of avg_p_recall</span></span>
<span id="cb45-2"><a href="#cb45-2" aria-hidden="true" tabindex="-1"></a><span class="fu">hist</span>(spaced_repetition_effectiveness<span class="sc">$</span>avg_p_recall, <span class="at">breaks =</span> <span class="dv">20</span>, <span class="at">main =</span> <span class="st">"Distribution of avg_p_recall"</span>, <span class="at">xlab =</span> <span class="st">"avg_p_recall"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="hp1_files/figure-html/unnamed-chunk-10-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>Considering the histogram is skewed left, it appears that the participants are recalling most of the words correctly. The mean of all average proportion session recalls is 0.8674 while the median exists at a high 0.9013. Therefore, the spaced repetition approach employed by Duolingo appears to be arguably effective. However, we should also look further into the different types of variables and how they may potentially affect the learning performances</p>
<p><strong>2. Are there any patterns in user performance based on time since the last practice?</strong></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb46"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb46-1"><a href="#cb46-1" aria-hidden="true" tabindex="-1"></a><span class="co"># We are going to be using the sample size 5000 because the original data frame has over 1.2 million observations and it will take too long for the plot codes to load with that data size</span></span>
<span id="cb46-2"><a href="#cb46-2" aria-hidden="true" tabindex="-1"></a>sample_size <span class="ot">&lt;-</span> <span class="dv">50000</span>  <span class="co"># Adjust as needed</span></span>
<span id="cb46-3"><a href="#cb46-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb46-4"><a href="#cb46-4" aria-hidden="true" tabindex="-1"></a><span class="co">#  The original dataset is too large to efficiently plot every value</span></span>
<span id="cb46-5"><a href="#cb46-5" aria-hidden="true" tabindex="-1"></a>sampled_data <span class="ot">&lt;-</span> <span class="fu">sample_n</span>(duo_data, sample_size)</span>
<span id="cb46-6"><a href="#cb46-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb46-7"><a href="#cb46-7" aria-hidden="true" tabindex="-1"></a>performance_vs_delta <span class="ot">&lt;-</span> sampled_data <span class="sc">|&gt;</span></span>
<span id="cb46-8"><a href="#cb46-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> delta, <span class="at">y =</span> p_recall)) <span class="sc">+</span></span>
<span id="cb46-9"><a href="#cb46-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">color =</span> <span class="st">"blue"</span>) <span class="sc">+</span></span>
<span id="cb46-10"><a href="#cb46-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">method =</span> <span class="st">"lm"</span>, <span class="at">se =</span> <span class="cn">FALSE</span>, <span class="at">color =</span> <span class="st">"red"</span>) <span class="sc">+</span></span>
<span id="cb46-11"><a href="#cb46-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"Time Since Last Practice (seconds)"</span>, <span class="at">y =</span> <span class="st">"Proportion of Correct Recalls"</span>, <span class="at">title =</span> <span class="st">"User Performance vs Time Since Last Practice"</span>)</span>
<span id="cb46-12"><a href="#cb46-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb46-13"><a href="#cb46-13" aria-hidden="true" tabindex="-1"></a><span class="co"># Display the plot</span></span>
<span id="cb46-14"><a href="#cb46-14" aria-hidden="true" tabindex="-1"></a>performance_vs_delta</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>`geom_smooth()` using formula = 'y ~ x'</code></pre>
</div>
<div class="cell-output-display">
<p><img src="hp1_files/figure-html/unnamed-chunk-11-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>The performance_vs_delta graph shows there is a slight negative connotation between performance and the time since the last practice.</p>
<p><strong>Bonus sub-question: Are participants more likely to recall a word with shorter spaced repetition time intervals?</strong></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb48"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb48-1"><a href="#cb48-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Create ggplot for avg_p_recall vs avg_delta with smoothed line</span></span>
<span id="cb48-2"><a href="#cb48-2" aria-hidden="true" tabindex="-1"></a>plot_spaced_rep <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(user_summary, <span class="fu">aes</span>(<span class="at">x =</span> avg_delta, <span class="at">y =</span> avg_p_recall)) <span class="sc">+</span></span>
<span id="cb48-3"><a href="#cb48-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>() <span class="sc">+</span></span>
<span id="cb48-4"><a href="#cb48-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">method =</span> <span class="st">"lm"</span>, <span class="at">se =</span> <span class="cn">FALSE</span>) <span class="sc">+</span>  <span class="co"># Add a linear regression line without confidence interval</span></span>
<span id="cb48-5"><a href="#cb48-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"Average Delta"</span>, <span class="at">y =</span> <span class="st">"Average p_recall"</span>, <span class="at">title =</span> <span class="st">"Average p_recall vs. Average Delta"</span>)</span>
<span id="cb48-6"><a href="#cb48-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb48-7"><a href="#cb48-7" aria-hidden="true" tabindex="-1"></a>plot_spaced_rep</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>`geom_smooth()` using formula = 'y ~ x'</code></pre>
</div>
<div class="cell-output-display">
<p><img src="hp1_files/figure-html/unnamed-chunk-12-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>According to the graph above, users generally perform better when the spaced repetition time intervals are shorter. This observation holds true across a range of delta values, from 0 seconds to up to 463 days. It implies that users may experience improved learning outcomes with consistent and frequent study sessions on Duolingo.</p>
<p><strong>3. Does the user interface language affect the user’s performance?</strong></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb50"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb50-1"><a href="#cb50-1" aria-hidden="true" tabindex="-1"></a>ui_language_performance <span class="ot">&lt;-</span> duo_data <span class="sc">|&gt;</span></span>
<span id="cb50-2"><a href="#cb50-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(ui_language) <span class="sc">|&gt;</span></span>
<span id="cb50-3"><a href="#cb50-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="at">avg_p_recall =</span> <span class="fu">mean</span>(p_recall))</span>
<span id="cb50-4"><a href="#cb50-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb50-5"><a href="#cb50-5" aria-hidden="true" tabindex="-1"></a>ui_language_performance</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 4 × 2
  ui_language avg_p_recall
  &lt;chr&gt;              &lt;dbl&gt;
1 English            0.895
2 Italian            0.910
3 Portuguese         0.899
4 Spanish            0.896</code></pre>
</div>
<div class="sourceCode cell-code" id="cb52"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb52-1"><a href="#cb52-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(ui_language_performance<span class="sc">$</span>avg_p_recall)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
 0.8950  0.8960  0.8975  0.8999  0.9014  0.9096 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb54"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb54-1"><a href="#cb54-1" aria-hidden="true" tabindex="-1"></a>standard_deviation <span class="ot">&lt;-</span> <span class="fu">sd</span>(ui_language_performance<span class="sc">$</span>avg_p_recall)</span>
<span id="cb54-2"><a href="#cb54-2" aria-hidden="true" tabindex="-1"></a>standard_deviation</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.006650745</code></pre>
</div>
<div class="sourceCode cell-code" id="cb56"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb56-1"><a href="#cb56-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(ui_language_performance, <span class="fu">aes</span>(<span class="at">x =</span> ui_language, <span class="at">y =</span> avg_p_recall)) <span class="sc">+</span></span>
<span id="cb56-2"><a href="#cb56-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_bar</span>(<span class="at">stat =</span> <span class="st">"identity"</span>, <span class="at">fill =</span> <span class="st">"skyblue"</span>, <span class="at">na.rm =</span> <span class="cn">TRUE</span>) <span class="sc">+</span></span>
<span id="cb56-3"><a href="#cb56-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>() <span class="sc">+</span></span>
<span id="cb56-4"><a href="#cb56-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"User Interface Language"</span>, <span class="at">y =</span> <span class="st">"Average Proportion of Correct Recalls"</span>, <span class="at">title =</span> <span class="st">"Impact of User Interface Language on Performance"</span>) <span class="sc">+</span> <span class="fu">coord_cartesian</span>(<span class="at">ylim =</span> <span class="fu">c</span>(<span class="fl">0.85</span>, <span class="dv">1</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="hp1_files/figure-html/unnamed-chunk-13-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>It seems that there is minimal variation in user performance across different user interface languages, as indicated by the low standard deviation observed for all languages. Furthermore, the plot depicting performance by language reveals only subtle differences between the bars, which become more apparent when zooming in on the range between 0.85 and 1.</p>
<p>Arguably, users who have Italian set as their user interface language exhibit slightly better performance compared to users with other languages.</p>
<p>Still, the differences are really minimal.</p>
<p>I am going to add new columns to our user_summary data frame. I will be specifying the languages each user is learning and the languages they use in their UI. This will be used when answering question 5.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb57"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb57-1"><a href="#cb57-1" aria-hidden="true" tabindex="-1"></a>user_learning <span class="ot">&lt;-</span> <span class="fu">distinct</span>(duo_data, user_id, learning_language)</span>
<span id="cb57-2"><a href="#cb57-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb57-3"><a href="#cb57-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb57-4"><a href="#cb57-4" aria-hidden="true" tabindex="-1"></a>user_learning <span class="ot">&lt;-</span> user_learning <span class="sc">|&gt;</span></span>
<span id="cb57-5"><a href="#cb57-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(user_id) <span class="sc">|&gt;</span></span>
<span id="cb57-6"><a href="#cb57-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarize</span>(<span class="at">learning =</span> <span class="fu">toString</span>(learning_language))</span>
<span id="cb57-7"><a href="#cb57-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb57-8"><a href="#cb57-8" aria-hidden="true" tabindex="-1"></a>user_summary <span class="ot">&lt;-</span> user_summary <span class="sc">|&gt;</span></span>
<span id="cb57-9"><a href="#cb57-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">left_join</span>(user_learning, <span class="at">by =</span> <span class="st">"user_id"</span>)</span>
<span id="cb57-10"><a href="#cb57-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb57-11"><a href="#cb57-11" aria-hidden="true" tabindex="-1"></a>user_ui_language <span class="ot">&lt;-</span> <span class="fu">distinct</span>(duo_data, user_id, ui_language)</span>
<span id="cb57-12"><a href="#cb57-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb57-13"><a href="#cb57-13" aria-hidden="true" tabindex="-1"></a>user_ui_language <span class="ot">&lt;-</span> user_ui_language <span class="sc">|&gt;</span></span>
<span id="cb57-14"><a href="#cb57-14" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(user_id) <span class="sc">|&gt;</span></span>
<span id="cb57-15"><a href="#cb57-15" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarize</span>(<span class="at">ui_languages =</span> <span class="fu">toString</span>(ui_language))</span>
<span id="cb57-16"><a href="#cb57-16" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb57-17"><a href="#cb57-17" aria-hidden="true" tabindex="-1"></a><span class="co"># Merge the ui_language information into user_summary</span></span>
<span id="cb57-18"><a href="#cb57-18" aria-hidden="true" tabindex="-1"></a>user_summary <span class="ot">&lt;-</span> user_summary <span class="sc">|&gt;</span></span>
<span id="cb57-19"><a href="#cb57-19" aria-hidden="true" tabindex="-1"></a>  <span class="fu">left_join</span>(user_ui_language, <span class="at">by =</span> <span class="st">"user_id"</span>)</span>
<span id="cb57-20"><a href="#cb57-20" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb57-21"><a href="#cb57-21" aria-hidden="true" tabindex="-1"></a>user_summary</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 115,222 × 7
   user_id avg_history_recall avg_p_recall num_occurrences avg_delta learning   
   &lt;fct&gt;                &lt;dbl&gt;        &lt;dbl&gt;           &lt;int&gt;     &lt;dbl&gt; &lt;chr&gt;      
 1 u:--N                0.875        0.810              32 15105609. German     
 2 u:--U                0.905        0.929               7  5608727  German     
 3 u:-_-                0.912        0.905             152   671605. German     
 4 u:-_D                0.929        0.5                14 12767600. Spanish    
 5 u:-3I                0.905        0.9                14   283420. French     
 6 u:-3n                0.894        0.830             124 11269398. Spanish    
 7 u:-4V                0.932        0.874             215  3142199. German, Fr…
 8 u:-4y                0.919        0.944              68  5354884. Spanish    
 9 u:-5I                0.801        0.885              39   629067. German     
10 u:-69                0.892        0.811              15 13550005. French     
# ℹ 115,212 more rows
# ℹ 1 more variable: ui_languages &lt;chr&gt;</code></pre>
</div>
</div>
<p><strong>4. What are the most challenging words for users?</strong></p>
<p>I will reuse the data frame from question 1.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb59"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb59-1"><a href="#cb59-1" aria-hidden="true" tabindex="-1"></a>top_challenging_lexemes <span class="ot">&lt;-</span> spaced_repetition_effectiveness <span class="sc">|&gt;</span></span>
<span id="cb59-2"><a href="#cb59-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">arrange</span>(avg_p_recall) <span class="sc">|&gt;</span></span>
<span id="cb59-3"><a href="#cb59-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">head</span>(<span class="dv">100</span>)</span>
<span id="cb59-4"><a href="#cb59-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb59-5"><a href="#cb59-5" aria-hidden="true" tabindex="-1"></a>top_challenging_lexemes</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 100 × 2
   lexeme_id                        avg_p_recall
   &lt;fct&gt;                                   &lt;dbl&gt;
 1 01887462f7ebffbd51e1ce584f52ab46            0
 2 032d211238829c77fcae70ba6cbd9baa            0
 3 0448efe1a8ce9a9a82591211c6851319            0
 4 056f2cd86a76d02956cc3b4166ddf8d5            0
 5 05bcf33b480493bba79420cd3fda19bf            0
 6 0849ef6f8c6a8bc3e852bba498399fd5            0
 7 0adb615b97a994c771898fd19a2824e4            0
 8 0bb66e53a0b008ca866b10f37819e48e            0
 9 114bb084c98f5ca1a1e1a4e4424c0940            0
10 11721ecdb20febdc3a42e12f21704502            0
# ℹ 90 more rows</code></pre>
</div>
</div>
<p><strong>Bonus sub-question: what type of words are participants are having most difficulty recalling?</strong></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb61"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb61-1"><a href="#cb61-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Merge top_challenging_lexemes with duo_data to get lexeme_string</span></span>
<span id="cb61-2"><a href="#cb61-2" aria-hidden="true" tabindex="-1"></a>challenging_lexemes_with_string <span class="ot">&lt;-</span> top_challenging_lexemes <span class="sc">|&gt;</span></span>
<span id="cb61-3"><a href="#cb61-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">left_join</span>(duo_data, <span class="at">by =</span> <span class="st">"lexeme_id"</span>) <span class="sc">|&gt;</span></span>
<span id="cb61-4"><a href="#cb61-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(lexeme_id, lexeme_string, p_recall)</span>
<span id="cb61-5"><a href="#cb61-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb61-6"><a href="#cb61-6" aria-hidden="true" tabindex="-1"></a><span class="co"># View the correlated lexeme_id and lexeme_string</span></span>
<span id="cb61-7"><a href="#cb61-7" aria-hidden="true" tabindex="-1"></a>challenging_lexemes_with_string</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 119 × 3
   lexeme_id                        lexeme_string                       p_recall
   &lt;fct&gt;                            &lt;chr&gt;                                  &lt;dbl&gt;
 1 01887462f7ebffbd51e1ce584f52ab46 dis/dire&lt;vblex&gt;&lt;pri&gt;&lt;p2&gt;&lt;sg&gt;               0
 2 032d211238829c77fcae70ba6cbd9baa &lt;*sf&gt;/limite&lt;n&gt;&lt;f&gt;&lt;*numb&gt;                  0
 3 0448efe1a8ce9a9a82591211c6851319 olhos/olho&lt;n&gt;&lt;m&gt;&lt;pl&gt;                       0
 4 056f2cd86a76d02956cc3b4166ddf8d5 revoir/revoir&lt;vblex&gt;&lt;inf&gt;                  0
 5 05bcf33b480493bba79420cd3fda19bf gruppen/gruppe&lt;n&gt;&lt;f&gt;&lt;pl&gt;&lt;dat&gt;              0
 6 0849ef6f8c6a8bc3e852bba498399fd5 beschluss/beschluss&lt;n&gt;&lt;m&gt;&lt;sg&gt;&lt;*cas…        0
 7 0adb615b97a994c771898fd19a2824e4 &lt;*sf&gt;/notion&lt;n&gt;&lt;f&gt;&lt;*numb&gt;                  0
 8 0adb615b97a994c771898fd19a2824e4 &lt;*sf&gt;/notion&lt;n&gt;&lt;f&gt;&lt;*numb&gt;                  0
 9 0bb66e53a0b008ca866b10f37819e48e parlais/parler&lt;vblex&gt;&lt;pii&gt;&lt;p2&gt;&lt;sg&gt;         0
10 0bb66e53a0b008ca866b10f37819e48e parlais/parler&lt;vblex&gt;&lt;pii&gt;&lt;p2&gt;&lt;sg&gt;         0
# ℹ 109 more rows</code></pre>
</div>
</div>
<p>Let’s find the most common sub strings (only alphabetical letters) that exists between &lt; and &gt; in lexeme_string. These sub strings usually tells us what kind of word did the user encounter in their duolingo exercise context. Was it a noun? verb? plural? singular? etc.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb63"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb63-1"><a href="#cb63-1" aria-hidden="true" tabindex="-1"></a>substrings <span class="ot">&lt;-</span> <span class="fu">str_extract_all</span>(challenging_lexemes_with_string<span class="sc">$</span>lexeme_string, <span class="st">"(?&lt;=&lt;)[^&lt;&gt;]+(?=&gt;)"</span>)</span>
<span id="cb63-2"><a href="#cb63-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb63-3"><a href="#cb63-3" aria-hidden="true" tabindex="-1"></a><span class="co"># Flatten the list of sub strings</span></span>
<span id="cb63-4"><a href="#cb63-4" aria-hidden="true" tabindex="-1"></a>all_substrings <span class="ot">&lt;-</span> <span class="fu">unlist</span>(substrings)</span>
<span id="cb63-5"><a href="#cb63-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb63-6"><a href="#cb63-6" aria-hidden="true" tabindex="-1"></a><span class="co"># Count the frequency of each sub string</span></span>
<span id="cb63-7"><a href="#cb63-7" aria-hidden="true" tabindex="-1"></a>substring_counts <span class="ot">&lt;-</span> <span class="fu">table</span>(all_substrings)</span>
<span id="cb63-8"><a href="#cb63-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb63-9"><a href="#cb63-9" aria-hidden="true" tabindex="-1"></a><span class="co"># Sort the sub strings by frequency in descending order</span></span>
<span id="cb63-10"><a href="#cb63-10" aria-hidden="true" tabindex="-1"></a>sorted_substrings <span class="ot">&lt;-</span> <span class="fu">sort</span>(substring_counts, <span class="at">decreasing =</span> <span class="cn">TRUE</span>)</span>
<span id="cb63-11"><a href="#cb63-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb63-12"><a href="#cb63-12" aria-hidden="true" tabindex="-1"></a>top_10_substrings <span class="ot">&lt;-</span> <span class="fu">head</span>(sorted_substrings, <span class="dv">10</span>)</span>
<span id="cb63-13"><a href="#cb63-13" aria-hidden="true" tabindex="-1"></a>top_10_substrings</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>all_substrings
    n    sg vblex *numb   *sf     f    pl     m   pri    p3 
   65    42    38    37    37    34    34    27    18    13 </code></pre>
</div>
</div>
<p>Here’s a breakdown of what each of the top 10 sub string tells about a word:</p>
<p>n: noun,</p>
<p>sg: singular form,</p>
<p>vblex: verb,</p>
<p>lexemes. *numb: related to numbers,</p>
<p>sf: the surface form is the same as the base form,</p>
<p>f: feminine gender,</p>
<p>pl: plural form,</p>
<p>m: masculine gender,</p>
<p>pri: primary form,</p>
<p>p3: third person singular,</p>
<p>These top 10 sub strings suggest that Duolingo users in this data set may be encountering most difficulties with nouns, verbs, gender distinctions, and possibly numerical concepts in their language learning exercises.</p>
<p><strong>5. Is there any correlation between the user’s history with a word and their performance in the current session?</strong></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb65"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb65-1"><a href="#cb65-1" aria-hidden="true" tabindex="-1"></a>history_vs_performance <span class="ot">&lt;-</span> sampled_data <span class="sc">|&gt;</span></span>
<span id="cb65-2"><a href="#cb65-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> history_seen, <span class="at">y =</span> p_recall)) <span class="sc">+</span></span>
<span id="cb65-3"><a href="#cb65-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">color =</span> <span class="st">"green"</span>) <span class="sc">+</span></span>
<span id="cb65-4"><a href="#cb65-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">method =</span> <span class="st">"lm"</span>, <span class="at">se =</span> <span class="cn">FALSE</span>, <span class="at">color =</span> <span class="st">"purple"</span>) <span class="sc">+</span></span>
<span id="cb65-5"><a href="#cb65-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>() <span class="sc">+</span></span>
<span id="cb65-6"><a href="#cb65-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"History Seen"</span>, <span class="at">y =</span> <span class="st">"Proportion of Correct Recalls"</span>, <span class="at">title =</span> <span class="st">"Relationship between History Seen and Performance"</span>)</span>
<span id="cb65-7"><a href="#cb65-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb65-8"><a href="#cb65-8" aria-hidden="true" tabindex="-1"></a><span class="co"># Displaying  the plot</span></span>
<span id="cb65-9"><a href="#cb65-9" aria-hidden="true" tabindex="-1"></a>history_vs_performance</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>`geom_smooth()` using formula = 'y ~ x'</code></pre>
</div>
<div class="cell-output-display">
<p><img src="hp1_files/figure-html/unnamed-chunk-18-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>It appears there are outliers (above 1000) for history_seen</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb67"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb67-1"><a href="#cb67-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Using filter to make a subset and remove the one outlier above 10000</span></span>
<span id="cb67-2"><a href="#cb67-2" aria-hidden="true" tabindex="-1"></a>duo_data_filtered <span class="ot">&lt;-</span> duo_data <span class="sc">|&gt;</span></span>
<span id="cb67-3"><a href="#cb67-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(history_seen <span class="sc">&lt;=</span> <span class="dv">1000</span>)</span>
<span id="cb67-4"><a href="#cb67-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb67-5"><a href="#cb67-5" aria-hidden="true" tabindex="-1"></a><span class="co"># Now 'duo_data_filtered' contains the data without outliers where a word has been seen over 1000 times</span></span>
<span id="cb67-6"><a href="#cb67-6" aria-hidden="true" tabindex="-1"></a>samp_data <span class="ot">&lt;-</span> <span class="fu">sample_n</span>(duo_data_filtered, sample_size)</span>
<span id="cb67-7"><a href="#cb67-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb67-8"><a href="#cb67-8" aria-hidden="true" tabindex="-1"></a>hist_vs_performance <span class="ot">&lt;-</span> samp_data <span class="sc">|&gt;</span></span>
<span id="cb67-9"><a href="#cb67-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> history_seen, <span class="at">y =</span> p_recall)) <span class="sc">+</span></span>
<span id="cb67-10"><a href="#cb67-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">color =</span> <span class="st">"green"</span>) <span class="sc">+</span></span>
<span id="cb67-11"><a href="#cb67-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">method =</span> <span class="st">"lm"</span>, <span class="at">se =</span> <span class="cn">FALSE</span>, <span class="at">color =</span> <span class="st">"purple"</span>) <span class="sc">+</span></span>
<span id="cb67-12"><a href="#cb67-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>() <span class="sc">+</span></span>
<span id="cb67-13"><a href="#cb67-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"History Seen"</span>, <span class="at">y =</span> <span class="st">"Proportion of Correct Recalls"</span>, <span class="at">title =</span> <span class="st">"Relationship between History Seen and Performance"</span>)</span>
<span id="cb67-14"><a href="#cb67-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb67-15"><a href="#cb67-15" aria-hidden="true" tabindex="-1"></a>hist_vs_performance</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>`geom_smooth()` using formula = 'y ~ x'</code></pre>
</div>
<div class="cell-output-display">
<p><img src="hp1_files/figure-html/unnamed-chunk-19-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>Surprisingly, there is also a slight negative relation between a user’s ability to recall a word and the number of times the word has already been studied/seen. Perhaps certain words are too difficult. Thus, a user may require more repetitions to fully learn the word(?). After all, it is common for the duolingo algorithm to show a word less if the user has a high recall rate on it after a few tries.</p>
<p><em>What if a user’s performance and training is not dependent on repetition but their previous accuracy score on the word?</em></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb69"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb69-1"><a href="#cb69-1" aria-hidden="true" tabindex="-1"></a>historyrecall_vs_performance <span class="ot">&lt;-</span> sampled_data <span class="sc">|&gt;</span></span>
<span id="cb69-2"><a href="#cb69-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> history_recall, <span class="at">y =</span> p_recall)) <span class="sc">+</span></span>
<span id="cb69-3"><a href="#cb69-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">color =</span> <span class="st">"blue"</span>) <span class="sc">+</span></span>
<span id="cb69-4"><a href="#cb69-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">method =</span> <span class="st">"lm"</span>, <span class="at">se =</span> <span class="cn">FALSE</span>, <span class="at">color =</span> <span class="st">"purple"</span>) <span class="sc">+</span></span>
<span id="cb69-5"><a href="#cb69-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>() <span class="sc">+</span></span>
<span id="cb69-6"><a href="#cb69-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"Proportion of History Recalls"</span>, <span class="at">y =</span> <span class="st">"Proportion of Correct Recalls"</span>, <span class="at">title =</span> <span class="st">"Relationship between Previous Performance and Tested Performance"</span>)</span>
<span id="cb69-7"><a href="#cb69-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb69-8"><a href="#cb69-8" aria-hidden="true" tabindex="-1"></a>historyrecall_vs_performance</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>`geom_smooth()` using formula = 'y ~ x'</code></pre>
</div>
<div class="cell-output-display">
<p><img src="hp1_files/figure-html/unnamed-chunk-20-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>The above graph suggests that for many words, a user’s session performance is correlated to the user’s history performance</p>
<p><em>How about we assess each user’s overall average performances</em></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb71"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb71-1"><a href="#cb71-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Comparing avg_p_recall and avg_history_recall for each user_id</span></span>
<span id="cb71-2"><a href="#cb71-2" aria-hidden="true" tabindex="-1"></a>user_perfom <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(user_summary, <span class="fu">aes</span>(<span class="at">x =</span> avg_p_recall, <span class="at">y =</span> avg_history_recall)) <span class="sc">+</span></span>
<span id="cb71-3"><a href="#cb71-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>() <span class="sc">+</span> </span>
<span id="cb71-4"><a href="#cb71-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">method =</span> <span class="st">"lm"</span>, <span class="at">se =</span> <span class="cn">FALSE</span>, <span class="at">color =</span> <span class="st">"blue"</span>) <span class="sc">+</span></span>
<span id="cb71-5"><a href="#cb71-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"Average p_recall"</span>, <span class="at">y =</span> <span class="st">"Average history_recall"</span>, <span class="at">title =</span> <span class="st">"Comparison of Recall Metrics"</span>)</span>
<span id="cb71-6"><a href="#cb71-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb71-7"><a href="#cb71-7" aria-hidden="true" tabindex="-1"></a>user_perfom</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>`geom_smooth()` using formula = 'y ~ x'</code></pre>
</div>
<div class="cell-output-display">
<p><img src="hp1_files/figure-html/unnamed-chunk-21-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>There is strong evidence suggesting that participants tend to perform well on their session recalls when they also excel in their history recalls.</p>
<p>Let’s remake the graph that shows the different types of UI languages</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb73"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb73-1"><a href="#cb73-1" aria-hidden="true" tabindex="-1"></a>user_perform <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(user_summary, <span class="fu">aes</span>(<span class="at">x =</span> avg_p_recall, <span class="at">y =</span> avg_history_recall, <span class="at">color =</span> ui_languages)) <span class="sc">+</span></span>
<span id="cb73-2"><a href="#cb73-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>() <span class="sc">+</span></span>
<span id="cb73-3"><a href="#cb73-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">method =</span> <span class="st">"lm"</span>, <span class="at">se =</span> <span class="cn">FALSE</span>, <span class="at">color =</span> <span class="st">"blue"</span>)</span>
<span id="cb73-4"><a href="#cb73-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"Average p_recall"</span>, <span class="at">y =</span> <span class="st">"Average history_recall"</span>, <span class="at">title =</span> <span class="st">"Comparison of Recall Metrics"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>$x
[1] "Average p_recall"

$y
[1] "Average history_recall"

$title
[1] "Comparison of Recall Metrics"

attr(,"class")
[1] "labels"</code></pre>
</div>
<div class="sourceCode cell-code" id="cb75"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb75-1"><a href="#cb75-1" aria-hidden="true" tabindex="-1"></a>user_perform </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>`geom_smooth()` using formula = 'y ~ x'</code></pre>
</div>
<div class="cell-output-display">
<p><img src="hp1_files/figure-html/unnamed-chunk-22-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb77"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb77-1"><a href="#cb77-1" aria-hidden="true" tabindex="-1"></a>user_perform <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(user_summary, <span class="fu">aes</span>(<span class="at">x =</span> avg_p_recall, <span class="at">y =</span> avg_history_recall, <span class="at">color =</span> ui_languages)) <span class="sc">+</span></span>
<span id="cb77-2"><a href="#cb77-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>() <span class="sc">+</span></span>
<span id="cb77-3"><a href="#cb77-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">method =</span> <span class="st">"lm"</span>, <span class="at">se =</span> <span class="cn">FALSE</span>, <span class="at">color =</span> <span class="st">"blue"</span>) <span class="sc">+</span></span>
<span id="cb77-4"><a href="#cb77-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"Average p_recall"</span>, <span class="at">y =</span> <span class="st">"Average history_recall"</span>, <span class="at">title =</span> <span class="st">"Comparison of Recall Metrics"</span>) <span class="sc">+</span></span>
<span id="cb77-5"><a href="#cb77-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">facet_wrap</span>(<span class="sc">~</span> ui_languages)</span>
<span id="cb77-6"><a href="#cb77-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb77-7"><a href="#cb77-7" aria-hidden="true" tabindex="-1"></a>user_perform</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>`geom_smooth()` using formula = 'y ~ x'</code></pre>
</div>
<div class="cell-output-display">
<p><img src="hp1_files/figure-html/unnamed-chunk-23-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>Overall, the separate plots indicate a consistent trend across various native speakers: participants tend to demonstrate strong performance in their session recalls when they already exhibit proficiency in their history recalls.</p>
</section>
<section id="summary-main-findings" class="level3">
<h3 class="anchored" data-anchor-id="summary-main-findings"><strong>Summary: Main Findings</strong></h3>
<ol type="1">
<li><p>The spaced repetition approach employed by Duolingo appears effective, as indicated by high proportions of correct word recalls.</p></li>
<li><p>User performance tends to decrease slightly with longer intervals since the last practice session, suggesting better performance with shorter intervals. Users generally perform better with shorter spaced repetition time intervals, implying improved learning outcomes with consistent study sessions.</p></li>
<li><p>The user interface language has minimal impact on user performance, with subtle differences observed among languages. However, users with Italian set as their UI language exhibit slightly better performance.</p></li>
<li><p>The most challenging words for users include nouns, verbs, and gender distinctions, suggesting difficulty with these concepts.</p></li>
<li><p>There’s a slight negative correlation between a user’s history with a word and their performance in the current session, indicating the need for more repetitions for certain words. On average, however, for each user, users tend to perform well in current sessions when they excel in previous ones, regardless of language or UI language.</p></li>
</ol>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->



</body></html>